#!/bin/sh
# Regenerates docs/CODEMAP.md: a compact per-file symbol index of src/.
# Run after adding/moving public functions so AI/code navigation can jump
# straight to file:line instead of searching the whole tree.
out=docs/CODEMAP.md
mkdir -p docs
{
echo "# Code map"
echo
echo "Generated by \`tools/codemap.sh\` — do not edit by hand."
echo "Format: one section per file: role (from its //! header), then"
echo "\`symbol:line\` for every top-level \`pub fn\` / \`pub const\` type."
echo
for f in src/*.zig; do
  lines=$(wc -l < "$f")
  echo "## $f ($lines lines)"
  role=$(grep -m1 '^//!' "$f" | sed 's^//! ^^')
  [ -n "$role" ] && echo "$role"
  syms=$(grep -n '^pub \(fn\|const\|var\)' "$f" \
    | sed 's/:pub fn \([A-Za-z0-9_]*\).*/ \1/;s/:pub const \([A-Za-z0-9_]*\).*/ \1/;s/:pub var \([A-Za-z0-9_]*\).*/ \1/' \
    | awk -F' ' '{printf "%s:%s, ", $2, $1}')
  [ -n "$syms" ] && echo "${syms%, }"
  echo
done
} > "$out"
echo "wrote $out"

# Append the spec index: every specs/NNN-name folder, comma-joined.
{
echo "## specs/ index"
echo "One folder per shipped slice (\`specs/NNN-name/spec.md\`):"
echo
ls specs | tr '\n' ' ' | fold -s -w 100
echo
} >> "$out"
